### ISSUE TITLE
Diseñar y documentar API de PUSH

### ISSUE THREAD

**Issue by Fedecolangelo** [addinkevin/taller2trips#142]

**Comment by addinkevin** [comment]
Para el modelo considerar:
- nombre
- descripcion (igual a como se venia haciendo)
- link 
- id_ciudad
- fecha (dd/mm/yyyy)
- hora (HH:MM)
El push tendrá asociada una imagen

**Comment by Fedecolangelo** [comment]
Ya esta el modelo docuementado en Swagger

**Comment by Fedecolangelo** [comment]
Ya esta la API documentada
