### ISSUE TITLE
API-01	Borrar atracciones cuando se borra la ciudad correspondiente

### ISSUE THREAD

**Issue by addinkevin** [addinkevin/taller2trips#15]
Al borrar una ciudad y luego ir a la sección de pestañas, las atracciones que tenían asociada esa ciudad muestran información invalida en el listado.

**Comment by Fedecolangelo** [comment]
Creo que la forma de solucionar esto es que cuando se borre una ciudad, se borren las atracciones correspondientes y que cuando se quiera borrar la ciudad el front-end muestra un warning.
Que te parece @addinkevin ?

**Comment by addinkevin** [comment]
Creo que sería mejor asignarles a esas atracciones una ciudad nula. Habría que confirmarlo con Ale.

**Comment by Fedecolangelo** [comment]
Dale, en un rato se lo pregunto

**Comment by Fedecolangelo** [comment]
Envíe la consulta a Alejandro.

**Comment by Fedecolangelo** [comment]
Alejandro: "Sobre el comportamiento de borrar ciudad, se puede borrar si no tiene
atracciones asociadas." en mail 02/04/2017

**Comment by Fedecolangelo** [comment]
@addinkevin ya estan develop el cambio, deberías recibir un error (codigo 409) en caso que quieras borrar una ciudad con atracciones.
