### ISSUE TITLE
Impedir el agregado de una ciudad repetida.

### ISSUE THREAD

**Issue by addinkevin** [addinkevin/taller2trips#57]
Esto es, no puede haber dos ciudades con igual nombre.

**Comment by Fedecolangelo** [comment]
Este tipo de cosas sumame en el ticket que las puedo resolver facil desde el backend. 
Vos después deberías manejar el error en el front.

**Comment by addinkevin** [comment]
Podría ser. Pero yo lo pensaba más por el lado de una validación al momento de hacer click en el submit, obligandolo al usuario a modificar el nombre de la ciudad ingresada.
Habría que validarlo con Ale si desea que no se puedan agregar ciudades con nombre repetido. Probablemente no.

**Comment by Fedecolangelo** [comment]
El tema es que puede haber ciudades con el mismo nombre. Cordoba esta en Argentina y en España. Incluso debe haber ciudades del mismo nombre en el mismo pais. De igual manera fijate ds hacerle @ a su user así lo ve (estoy con el celu y no me estaría funcionando el autocompletado de usuarios con el @)
