### ISSUE TITLE
Borrado inmediato de audio/imagen/video

### ISSUE THREAD

**Issue by addinkevin** [addinkevin/taller2trips#68]
Validar con Alejandro cuál es el funcionamiento deseado. Desde el punto de vista de usabilidad, sería mejor que se envíe todo cuando se hace click en Agregar/Guardar.

**Comment by Fedecolangelo** [comment]
Concuerdo con lo de agregar/guardad. 
Si ya agregaste a ale al repo, referencialo con @ para que le llegue la notificación
