### ISSUE TITLE
BACK Al borrar una atracción debería borrar el contenido asociado

### ISSUE THREAD

**Issue by Fedecolangelo** [addinkevin/taller2trips#75]
Me refiero a que debería disparar el DELETE de todos sus videos, imagenes y audios asociados.

**Comment by addinkevin** [comment]
@Fedecolangelo Creí que esto lo hacias desde el back. Creo que es más facil de esta forma.

**Comment by Fedecolangelo** [comment]
Bueno, lo tomo yo.
