### ISSUE TITLE
En el request de atracción debería haber algun indicativo si existe el recurso video o no.

### ISSUE THREAD

**Issue by addinkevin** [addinkevin/taller2trips#83]
Probablemente este issue se cancele el prox sprint dado que se va a tener que agregar multiple videos.

**Comment by Fedecolangelo** [comment]
@addinkevin porque no haces lo que hace @Seba0703 
Seba, nos podes dar una mano para comentarnos como haces esto vos?

**Comment by Fedecolangelo** [comment]
Definimos que se cheque en función del código de respuesta HTTP.
